[build]
  command = "npm run build"
  functions = "apps/ui/netlify/functions"
  publish = "apps/ui/.next"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  directory = "apps/ui/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev:ui"
  targetPort = 3000
  port = 8888
  publish = "apps/ui/.next"
  autoLaunch = false
